### ISSUE TITLE
encountered error when bringing up docker-compose

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/aries-playground#12]
An error occured when bringing up system. Cannot pinpoint the issue. Is there additional logs that are needed?

*** command line ***
$ docker-compose up
Starting agent1.webhook           ... done
Starting agent2.webhook           ... done
Starting agent3.localhost         ... done
Starting aries-playground_nginx_1 ... done
Starting agent3.webhook           ... done
Starting agent1.localhost         ... done
Starting agent2.localhost         ... done
Attaching to aries-playground_nginx_1, agent3.localhost, agent2.localhost, agent1.localhost, agent3.webhook, agent1.webhook, agent2.webhook
agent3.webhook      |  * Serving Flask app "app" (lazy loading)
agent3.webhook      |  * Environment: production
agent3.webhook      |    WARNING: Do not use the development server in a production environment.
agent3.webhook      |    Use a production WSGI server instead.
agent3.webhook      |  * Debug mode: on
agent2.webhook      |  * Serving Flask app "app" (lazy loading)
agent2.webhook      |  * Environment: production
agent2.webhook      |    WARNING: Do not use the development server in a production environment.
agent2.webhook      |    Use a production WSGI server instead.
agent2.webhook      |  * Debug mode: on
agent1.webhook      |  * Serving Flask app "app" (lazy loading)
agent1.webhook      |  * Environment: production
agent1.webhook      |    WARNING: Do not use the development server in a production environment.
agent1.webhook      |    Use a production WSGI server instead.
agent1.webhook      |  * Debug mode: on
agent3.localhost    | usage: aca-py start [-h] [--admin <host> <port>] [--admin-api-key <api-key>]
agent3.localhost    |                     [--admin-insecure-mode] [--no-receive-invites]
agent3.localhost    |                     [--help-link <help-url>] [--webhook-url <url>] [--debug]
agent3.localhost    |                     [--debug-seed <debug-did-seed>] [--debug-connections]
agent3.localhost    |                     [--debug-credentials] [--debug-presentations] [--invite]
agent3.localhost    |                     [--invite-role <role>] [--invite-label <label>]
agent3.localhost    |                     [--invite-multi-use] [--invite-public]
agent3.localhost    |                     [--test-suite-endpoint <endpoint>] [--auto-accept-invites]
agent3.localhost    |                     [--auto-accept-requests] [--auto-respond-messages]
agent3.localhost    |                     [--auto-respond-credential-proposal]
agent3.localhost    |                     [--auto-respond-credential-offer]
agent3.localhost    |                     [--auto-respond-credential-request]
agent3.localhost    |                     [--auto-respond-presentation-proposal]
agent3.localhost    |                     [--auto-respond-presentation-request]
agent3.localhost    |                     [--auto-store-credential] [--auto-verify-presentation]
agent3.localhost    |                     [--plugin <module>] [--storage-type <storage-type>]
agent3.localhost    |                     [-e <endpoint> [<endpoint> ...]] [--read-only-ledger]
agent3.localhost    |                     [--tails-server-base-url <tails-server-base-url>]
agent3.localhost    |                     [--ledger-pool-name <ledger-pool-name>]
agent3.localhost    |                     [--genesis-transactions <genesis-transactions>]
agent3.localhost    |                     [--genesis-file <genesis-file>]
agent3.localhost    |                     [--genesis-url <genesis-url>]
agent3.localhost    |                     [--log-config <path-to-config>] [--log-file <log-file>]
agent3.localhost    |                     [--log-level <log-level>] [--auto-ping-connection]
agent3.localhost    |                     [--invite-base-url <base-url>] [--monitor-ping]
agent3.localhost    |                     [--public-invites] [--timing] [--timing-log <log-path>]
agent3.localhost    |                     [--trace] [--trace-target <trace-target>]
agent3.localhost    |                     [--trace-tag <trace-tag>] [--trace-label <trace-label>]
agent3.localhost    |                     [--preserve-exchange-records] -it <module> <host> <port>
agent3.localhost    |                     -ot <module> [-l <label>]
agent3.localhost    |                     [--max-message-size <message-size>]
agent3.localhost    |                     [--enable-undelivered-queue]
agent3.localhost    |                     [--max-outbound-retry MAX_OUTBOUND_RETRY]
agent3.localhost    |                     [--seed <wallet-seed>] [--wallet-local-did]
agent3.localhost    |                     [--wallet-key <wallet-key>]
agent3.localhost    |                     [--wallet-rekey <wallet-rekey>]
agent3.localhost    |                     [--wallet-name <wallet-name>]
agent3.localhost    |                     [--wallet-type <wallet-type>]
agent3.localhost    |                     [--wallet-storage-type <storage-type>]
agent3.localhost    |                     [--wallet-storage-config <storage-config>]
agent3.localhost    |                     [--wallet-storage-creds <storage-creds>]
agent3.localhost    |                     [--replace-public-did]
agent3.localhost    | aca-py start: error: the following arguments are required: -it/--inbound-transport, -ot/--outbound-transport
agent3.localhost    | ./startup.sh: line 2: -it: command not found
agent3.localhost    | ./startup.sh: line 3: -ot: command not found
agent3.localhost    | ./startup.sh: line 4: -e: command not found
agent3.localhost    | ./startup.sh: line 5: --label: command not found
agent3.localhost    | ./startup.sh: line 6: --admin: command not found
agent3.localhost    | ./startup.sh: line 7: --admin-insecure-mode: command not found
agent3.localhost    | ./startup.sh: line 8: --auto-accept-requests: command not found
agent3.localhost    | ./startup.sh: line 9: --auto-respond-credential-proposal: command not found
agent3.localhost    | ./startup.sh: line 10: --auto-respond-presentation-proposal: command not found
agent3.localhost    | ./startup.sh: line 11: --genesis-url: command not found
agent3.localhost    | ./startup.sh: line 12: --wallet-type: command not found
agent3.localhost    | ./startup.sh: line 13: --wallet-name: command not found
agent3.localhost    | ./startup.sh: line 14: --webhook-url: command not found
agent2.localhost    | usage: aca-py start [-h] [--admin <host> <port>] [--admin-api-key <api-key>]
agent2.localhost    |                     [--admin-insecure-mode] [--no-receive-invites]
agent2.localhost    |                     [--help-link <help-url>] [--webhook-url <url>] [--debug]
agent2.localhost    |                     [--debug-seed <debug-did-seed>] [--debug-connections]
agent2.localhost    |                     [--debug-credentials] [--debug-presentations] [--invite]
agent2.localhost    |                     [--invite-role <role>] [--invite-label <label>]
agent2.localhost    |                     [--invite-multi-use] [--invite-public]
agent2.localhost    |                     [--test-suite-endpoint <endpoint>] [--auto-accept-invites]
agent2.localhost    |                     [--auto-accept-requests] [--auto-respond-messages]
agent2.localhost    |                     [--auto-respond-credential-proposal]
agent2.localhost    |                     [--auto-respond-credential-offer]
agent2.localhost    |                     [--auto-respond-credential-request]
agent2.localhost    |                     [--auto-respond-presentation-proposal]
agent2.localhost    |                     [--auto-respond-presentation-request]
agent2.localhost    |                     [--auto-store-credential] [--auto-verify-presentation]
agent2.localhost    |                     [--plugin <module>] [--storage-type <storage-type>]
agent2.localhost    |                     [-e <endpoint> [<endpoint> ...]] [--read-only-ledger]
agent2.localhost    |                     [--tails-server-base-url <tails-server-base-url>]
agent2.localhost    |                     [--ledger-pool-name <ledger-pool-name>]
agent2.localhost    |                     [--genesis-transactions <genesis-transactions>]
agent2.localhost    |                     [--genesis-file <genesis-file>]
agent2.localhost    |                     [--genesis-url <genesis-url>]
agent2.localhost    |                     [--log-config <path-to-config>] [--log-file <log-file>]
agent2.localhost    |                     [--log-level <log-level>] [--auto-ping-connection]
agent2.localhost    |                     [--invite-base-url <base-url>] [--monitor-ping]
agent2.localhost    |                     [--public-invites] [--timing] [--timing-log <log-path>]
agent2.localhost    |                     [--trace] [--trace-target <trace-target>]
agent2.localhost    |                     [--trace-tag <trace-tag>] [--trace-label <trace-label>]
agent2.localhost    |                     [--preserve-exchange-records] -it <module> <host> <port>
agent2.localhost    |                     -ot <module> [-l <label>]
agent2.localhost    |                     [--max-message-size <message-size>]
agent2.localhost    |                     [--enable-undelivered-queue]
agent2.localhost    |                     [--max-outbound-retry MAX_OUTBOUND_RETRY]
agent2.localhost    |                     [--seed <wallet-seed>] [--wallet-local-did]
agent2.localhost    |                     [--wallet-key <wallet-key>]
agent2.localhost    |                     [--wallet-rekey <wallet-rekey>]
agent2.localhost    |                     [--wallet-name <wallet-name>]
agent2.localhost    |                     [--wallet-type <wallet-type>]
agent2.localhost    |                     [--wallet-storage-type <storage-type>]
agent2.localhost    |                     [--wallet-storage-config <storage-config>]
agent2.localhost    |                     [--wallet-storage-creds <storage-creds>]
agent2.localhost    |                     [--replace-public-did]
agent2.localhost    | aca-py start: error: the following arguments are required: -it/--inbound-transport, -ot/--outbound-transport
agent3.localhost exited with code 127
agent2.localhost    | ./startup.sh: line 2: -it: command not found
agent2.localhost    | ./startup.sh: line 3: -ot: command not found
agent2.localhost    | ./startup.sh: line 4: -e: command not found
agent2.localhost    | ./startup.sh: line 5: --label: command not found
agent2.localhost    | ./startup.sh: line 6: --admin: command not found
agent2.localhost    | ./startup.sh: line 7: --admin-insecure-mode: command not found
agent2.localhost    | ./startup.sh: line 8: --auto-accept-requests: command not found
agent2.localhost    | ./startup.sh: line 9: --auto-respond-credential-proposal: command not found
agent2.localhost    | ./startup.sh: line 10: --auto-respond-presentation-proposal: command not found
agent2.localhost    | ./startup.sh: line 11: --genesis-url: command not found
agent2.localhost    | ./startup.sh: line 12: --wallet-type: command not found
agent2.localhost    | ./startup.sh: line 13: --wallet-name: command not found
agent2.localhost    | ./startup.sh: line 14: --webhook-url: command not found
agent1.localhost    | usage: aca-py start [-h] [--admin <host> <port>] [--admin-api-key <api-key>]
agent1.localhost    |                     [--admin-insecure-mode] [--no-receive-invites]
agent1.localhost    |                     [--help-link <help-url>] [--webhook-url <url>] [--debug]
agent1.localhost    |                     [--debug-seed <debug-did-seed>] [--debug-connections]
agent1.localhost    |                     [--debug-credentials] [--debug-presentations] [--invite]
agent1.localhost    |                     [--invite-role <role>] [--invite-label <label>]
agent1.localhost    |                     [--invite-multi-use] [--invite-public]
agent1.localhost    |                     [--test-suite-endpoint <endpoint>] [--auto-accept-invites]
agent1.localhost    |                     [--auto-accept-requests] [--auto-respond-messages]
agent1.localhost    |                     [--auto-respond-credential-proposal]
agent1.localhost    |                     [--auto-respond-credential-offer]
agent1.localhost    |                     [--auto-respond-credential-request]
agent1.localhost    |                     [--auto-respond-presentation-proposal]
agent1.localhost    |                     [--auto-respond-presentation-request]
agent1.localhost    |                     [--auto-store-credential] [--auto-verify-presentation]
agent1.localhost    |                     [--plugin <module>] [--storage-type <storage-type>]
agent1.localhost    |                     [-e <endpoint> [<endpoint> ...]] [--read-only-ledger]
agent1.localhost    |                     [--tails-server-base-url <tails-server-base-url>]
agent1.localhost    |                     [--ledger-pool-name <ledger-pool-name>]
agent1.localhost    |                     [--genesis-transactions <genesis-transactions>]
agent1.localhost    |                     [--genesis-file <genesis-file>]
agent1.localhost    |                     [--genesis-url <genesis-url>]
agent1.localhost    |                     [--log-config <path-to-config>] [--log-file <log-file>]
agent1.localhost    |                     [--log-level <log-level>] [--auto-ping-connection]
agent1.localhost    |                     [--invite-base-url <base-url>] [--monitor-ping]
agent1.localhost    |                     [--public-invites] [--timing] [--timing-log <log-path>]
agent1.localhost    |                     [--trace] [--trace-target <trace-target>]
agent1.localhost    |                     [--trace-tag <trace-tag>] [--trace-label <trace-label>]
agent1.localhost    |                     [--preserve-exchange-records] -it <module> <host> <port>
agent1.localhost    |                     -ot <module> [-l <label>]
agent1.localhost    |                     [--max-message-size <message-size>]
agent1.localhost    |                     [--enable-undelivered-queue]
agent1.localhost    |                     [--max-outbound-retry MAX_OUTBOUND_RETRY]
agent1.localhost    |                     [--seed <wallet-seed>] [--wallet-local-did]
agent1.localhost    |                     [--wallet-key <wallet-key>]
agent1.localhost    |                     [--wallet-rekey <wallet-rekey>]
agent1.localhost    |                     [--wallet-name <wallet-name>]
agent1.localhost    |                     [--wallet-type <wallet-type>]
agent1.localhost    |                     [--wallet-storage-type <storage-type>]
agent1.localhost    |                     [--wallet-storage-config <storage-config>]
agent1.localhost    |                     [--wallet-storage-creds <storage-creds>]
agent1.localhost    |                     [--replace-public-did]
agent1.localhost    | aca-py start: error: the following arguments are required: -it/--inbound-transport, -ot/--outbound-transport
agent1.localhost    | ./startup.sh: line 2: -it: command not found
agent1.localhost    | ./startup.sh: line 3: -ot: command not found
agent1.localhost    | ./startup.sh: line 4: -e: command not found
agent1.localhost    | ./startup.sh: line 5: --label: command not found
agent1.localhost    | ./startup.sh: line 6: --admin: command not found
agent1.localhost    | ./startup.sh: line 7: --admin-insecure-mode: command not found
agent1.localhost    | ./startup.sh: line 8: --auto-accept-requests: command not found
agent1.localhost    | ./startup.sh: line 9: --auto-respond-credential-proposal: command not found
agent1.localhost    | ./startup.sh: line 10: --auto-respond-presentation-proposal: command not found
agent1.localhost    | ./startup.sh: line 11: --genesis-url: command not found
agent1.localhost    | ./startup.sh: line 12: --wallet-type: command not found
agent1.localhost    | ./startup.sh: line 13: --wallet-name: command not found
agent1.localhost    | ./startup.sh: line 14: --webhook-url: command not found
agent2.localhost exited with code 127
agent1.localhost exited with code 127

**Comment by georgepadayatti** [comment]
Unable to reproduce the error. Noting that the error occurred while running in MinGW from windows 10.
