### ISSUE TITLE
Name of agents do not align with docker-compose.yml

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/aries-playground#19]
The agent names do not align so you cannot run the same commands as described. Either the yaml is modified or the README. Since this playground is tied to igrant webpage, https://docs.igrant.io/ssi/ssi-apg/, suggest to align the README.

**Comment by Selbin** [comment]
Under investigation

**Comment by Selbin** [comment]
@JanLin  Where did you find the change, Is it in the Readme.md file in the repo or in  https://docs.igrant.io/ssi/ssi-apg/

**Comment by JanLin** [comment]
I think the Readme.md file in the repo should be changed since it is out of sync with the docker-compose.yml.

**Comment by lalc** [comment]
@Selbin will you close this issue if its complete?

**Comment by Selbin** [comment]
Updated Readme.md
