### ISSUE TITLE
New igrantio images not publically accessible

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/aries-playground#21]
Checking hub.docker.com the images aries-agent is not available. Also how the images were built should be available or PR to the original master like the aries-agent.

**Comment by georgepadayatti** [comment]
The images are publicly available. You can browse them here - https://hub.docker.com/u/igrantio

**Comment by georgepadayatti** [comment]
The Dockerfile is already public. You can find it here - https://github.com/decentralised-dataexchange/aries-cloudagent-python/blob/wip/igrantio-operator/docker/Dockerfile.scratch

**Comment by JanLin** [comment]
I tried to search on igrantio but not possible. Had to use container then it worked. My mistake. Can we add a basic description like bcgov with references?

https://hub.docker.com/r/bcgovimages/aries-cloudagent

**Comment by georgepadayatti** [comment]
I also searched, for some reason it is not showing up in search results, although the organisation and images are public. Ok will add a description.
