### ISSUE TITLE
Clarify step (2) that von network is allready running indy.igrant.io

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/aries-playground#8]
Please clarify that step (2) uses external indy.igrant.io. Proposed text.

2. Von network is already running through indy.igrant.io and yaml file configuring docker-compose in next step points at that external ledger. If you will use your own ledger then you need to update the yaml file in next step to point at the local ledger. Refer to xxx for setting up own ledger.

**Comment by lalc** [comment]
The confusing is because we use the name von_von for the network. It doesn't have anything to do with indy network running or not. This is actually for providing network isolation

Hence, will rename von-von with aries-playground-nw.

**Comment by lalc** [comment]
Will use this issue to rename von-von with  aries-playground-nw in the README.md and the docker-compose.yaml file.
