### ISSUE TITLE
docker-compose up in step (3) gives error von_von not found

### ISSUE THREAD

**Issue by JanLin** [decentralised-dataexchange/aries-playground#9]
Attempted to run docker-compose but failed. Unclear what is issue if setup uses indy.igrant.io which should be running.

$ docker-compose up
Network von_von declared as external, but could not be found. Please create the network manually using `docker network create von_von` and try again.

**Comment by georgepadayatti** [comment]
Yes a **docker network** must be created first to isolate containers within that network. This is not related to Indy nodes running or not.

So for creating a docker network you can use the command `docker network create von_von`
